from selenium import webdriver

driver = webdriver.Chrome()
driver.get('https://github.com/')
signIn = driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/div[2]/a[1]')
signIn.click()
usernameField = driver.find_element_by_xpath('//*[@id="login_field"]')
usernameField.send_keys('secret_username')
passwordField = driver.find_element_by_xpath('//*[@id="password"]')
passwordField.send_keys('secret_password')
submit = driver.find_element_by_xpath('//*[@id="login"]/div[4]/form/div/input[12]')
submit.click()
newButton = driver.find_element_by_xpath('//*[@id="repos-container"]/h2/a')
newButton.click()
RepositoryField=driver.find_element_by_xpath('//*[@id="repository_name"]')
RepositoryField.send_keys('MyRepo')
RepoDesc=driver.find_element_by_xpath('//*[@id="repository_description"]')
RepoDesc.send_keys('demo')
public=driver.find_element_by_xpath('//*[@id="repository_visibility_public"]')
public.click()
createRepo = driver.find_element_by_xpath('//*[@id="new_repository"]/div[4]/button')
createRepo.click()
